language: objective-c
rvm:
  - 2.1.2

before_install:
  - git submodule update --init

env:
  matrix:
    - BUILD_SDK_VERSION="8.1" SIMULATOR_VERSIONS="8.1,7.1" SIMULATOR_DEVICES="iPhone 5,iPhone 5s"

script: rake travis

