language: objective-c  #1
osx_image: xcode8.3.3 #2
xcode_project: Replicon.xcodeproj #3
xcode_scheme: Replicon #4
xcode_sdk: iphonesimulator10.3 #5

language: objective-c
script:
  - xctool -project Replicon.xcodeproj -scheme Replicon build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
