CREATE TABLE "time_punch" (
"date" DATE NOT NULL,
"action_type" VARCHAR NOT NULL,
"user_uri" VARCHAR NOT NULL,
"uri" VARCHAR,
"break_type_name" VARCHAR,
"break_type_uri" VARCHAR,
"client_name" VARCHAR ,
"project_name" VARCHAR ,
"task_name" VARCHAR ,
"client_uri" VARCHAR ,
"project_uri" VARCHAR ,
"task_uri" VARCHAR ,
"location_latitude" FLOAT,
"location_longitude" FLOAT,
"location_horizontal_accuracy" FLOAT,
"address" VARCHAR,
"image_url" VARCHAR,
"image" BLOB,
"offline" BOOL,
"activity_name" VARCHAR,
"activity_uri" VARCHAR,
"punchSyncStatus" NUMERIC,
"lastSyncTime" DATETIME,
"request_id" VARCHAR  NOT NULL,
PRIMARY KEY("user_uri", "date")
);
